### ISSUE TITLE
remove  duplicate swagger declaration from 07-open-match-default-evaluator.yaml

### ISSUE THREAD

**Issue by dzmitry-lahoda** [googleforgames/open-match#1389]
**What happened**:

```
merging resources from '07-open-match-default-evaluator.yaml': may not add resource with an already registered id: ~G_v1_Service|open-match|open-match-swaggerui\"\n\t* loader.New error: \"error loading 07-open-match-default-evaluator.yaml with git: url lacks orgRepo: 07-open-match-default-evaluator.yaml, dir: got file '07-open-match-default-evaluator.yaml'
```

**What you expected to happen**:

- merge success

**How to reproduce it (as minimally and precisely as possible)**:

- reference files from https://open-match.dev/site/docs/installation/yaml/#install-the-default-evaluator into kustomize
- run kustomize

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 01-open-match-core.yaml
  - 06-open-match-override-configmap.yaml
  - 07-open-match-default-evaluator.yaml
```

**Anything else we need to know?**:

**Output of `kubectl version`**:

{Version:kustomize/v3.9.1 GitCommit:7439f1809e5ccd4677ed52be7f98f2ad75122a93 BuildDate:2020-12-29T19:25:35Z GoOs:windows GoArch:amd64}

**Open Match Release Version**:
- as by link

**Install Method(yaml/helm):**:
yaml

**Conflicted resource**

```yaml
kind: Service
apiVersion: v1
metadata:
  name: open-match-swaggerui
  namespace: open-match
  annotations:
    chart: open-match-1.2.0
    heritage: Helm
  labels:
    app: open-match
    component: swaggerui
    release: open-match
spec:
  selector:
    app: open-match
    component: swaggerui
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 51500
```

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-match-swaggerui
  namespace: open-match
  annotations:
    chart: open-match-1.2.0
    heritage: Helm
  labels:
    app: open-match
    component: swaggerui
    release: open-match
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-match
      component: swaggerui
  template:
    metadata:
      namespace: open-match
      annotations:
        chart: open-match-1.2.0
        heritage: Helm
      labels:
        app: open-match
        component: swaggerui
        release: open-match
    spec:
      
      volumes:
        
        - name: om-config-volume-default
          configMap:
            name: open-match-configmap-default
        - name: om-config-volume-override
          configMap:
            name: open-match-configmap-override
        
      serviceAccountName: open-match-unprivileged-service
      containers:
      - name: open-match-swaggerui
        volumeMounts:
          
          - name: om-config-volume-default
            mountPath: /app/config/default
          - name: om-config-volume-override
            mountPath: /app/config/override
          
        image: "gcr.io/open-match-public-images/openmatch-swaggerui:1.2.0"
        ports:
        - name: http
          containerPort: 51500
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /healthz
            port: 51500
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /healthz?readiness=true
            port: 51500
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 2
```
