### ISSUE TITLE
Query Tickets return nothing

### ISSUE THREAD

**Issue by lihaif** [googleforgames/open-match#1420]
**What happened**:
We found that sometimes the Open Match Query service does not return tickets like below. I inserted a ticket through Open Match Frontend pod. Then I tried to query it through the Open Match Query pod, but it returns nothing.

This does not always happen. But we saw this issue several times.

```
kubectl port-forward wardemo-open-match-query-78f78f468-spbd4 51503 -n wardemo
kubectl port-forward wardemo-open-match-frontend-7d6f9f9dfd-tff59 51504 -n wardemo
 
d_li@AU1-WW-192 MINGW64 /c/lhf/perforce/wardemo_dl
$ curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{"ticket": {"id": "b","search_fields":{"string_args":{"type":"test"}},"extensions":{}}}' http://localhost:51504/v1/frontendservice/tickets
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   211  100   124  100    87    253    177 --:--:-- --:--:-- --:--:--   431{"id":"c51uluqaeraj7vh9j2sg","search_fields":{"string_args":{"type":"test"}},"create_time":"2021-09-17T01:10:19.616478123Z"}
(python38vm2)
d_li@AU1-WW-192 MINGW64 /c/lhf/perforce/wardemo_dl
$ curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{"pool": {"name": "test","string_equals_filters":[{"string_arg":"type","value":"test"}]}}' http://localhost:51503/v1/queryservice/tickets:query
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    89    0     0  100    89      0    180 --:--:-- --:--:-- --:--:--   181
```

I suspect that Open Match Frontend pod is using a different Redis node to the Open Match Query pod. And for some reason, those 2 nodes are not in sync. I did the below change in the values.yaml passing to the helm chart to only leave one Redis node. And the Open Match Query pod start to return the ticket after this change.
```
  open-match:
    redis:
      cluster:
        slaveCount: 1
```

**What you expected to happen**:

We want to have consistent results no matter how many Redis nodes are started in the cluster.

**How to reproduce it (as minimally and precisely as possible)**:

We do not know how to exactly recreate this issue. Most time it worked correctly with the default deployment. But sometimes it happened.

**Anything else we need to know?**:

**Output of `kubectl version`**:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:38:50Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T20:59:07Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
```

**Cloud Provider/Platform (AKS, GKE, Minikube etc.)**: 

**Open Match Release Version**:
We are using Open Match 1.2.0.

**Install Method(yaml/helm):**:
We use helm with the below values to deploy Open Match.

```
  open-match:
    global:
      kubernetes:
        horizontalPodAutoScaler:
          # There isn't a way of disabling the autoscaler in OM, so default to 1
          maxReplicas: 1
    redis:
      master:
        persistence:
          enabled: false
      slave:
        persistence:
          enabled: false
```
