### ISSUE TITLE
PersistentVolumes and PersistentVolumeClaims persist even after helm uninstall

### ISSUE THREAD

**Issue by jhowcrof** [googleforgames/open-match#1477]
Hi,

We started encountering a problem where open-match couldn't start successfully. After digging around we found that the redis data volumes are never reset, even after making many changes and uninstalling from helm many times. This meant we had millions of tickets in redis upon start-up. Example:

```
redis-data-open-match-redis-node-0   Bound    pvc-c94f7e4b-4543-4e8d-985e-cee49710e32b   8Gi        RWO            standard       115d
redis-data-open-match-redis-node-1   Bound    pvc-3af3f3f5-d29d-4b0e-808d-a1fedc3304db   8Gi        RWO            standard       115d
redis-data-open-match-redis-node-2   Bound    pvc-146917d1-ceab-4331-9163-01807a19290f   8Gi        RWO            standard       8d
```

and 

```
pvc-359a9f92-996f-4ee1-ba42-539a497c0a1c   8Gi        RWO            Delete           Bound    open-match/redis-data-open-match-redis-node-1   standard                27d
pvc-a934b590-70bf-47b9-bd9c-e6f3ec186fec   8Gi        RWO            Delete           Bound    open-match/redis-data-open-match-redis-node-2   standard                6d19h
pvc-f9bb0538-0b30-4d84-8bbc-6d3f604b985f   8Gi        RWO            Delete           Bound    open-match/redis-data-open-match-redis-node-0   standard                27d
```

It is unexpected that any data would remain after installing.

**Comment by jhowcrof** [comment]
Expected behavior:

`helm uninstall open-match -n open-match` would delete the persistent volumes

Actual behavior:

Redis data sticks around.

**Comment by jhowcrof** [comment]
open-match values used are similar to the production helm values provided:

```
swaggerui: &swaggerui
  hostName:
  httpPort: 51500
  portType: ClusterIP
  replicas: 1
  image: openmatch-swaggerui
query: &query
  hostName:
  grpcPort: 50503
  httpPort: 51503
  portType: ClusterIP
  replicas: 3
  image: openmatch-query
frontend: &frontend
  hostName:
  grpcPort: 50504
  httpPort: 51504
  portType: ClusterIP
  replicas: 3
  image: openmatch-frontend
backend: &backend
  hostName:
  grpcPort: 50505
  httpPort: 51505
  portType: ClusterIP
  replicas: 3
  image: openmatch-backend
synchronizer: &synchronizer
  hostName:
  grpcPort: 50506
  httpPort: 51506
  portType: ClusterIP
  replicas: 1
  image: openmatch-synchronizer
evaluator: &evaluator
  hostName:
  grpcPort: 50508
  httpPort: 51508
  replicas: 3
function: &function
  hostName:
  grpcPort: 50502
  httpPort: 51502
  replicas: 3

# Specifies the location and name of the Open Match application-level config volumes.
# Used in template: `openmatch.volumemounts.configs` and `openmatch.volumes.configs` under `templates/_helpers.tpl` file.
configs:
  default:
    volumeName: om-config-volume-default
    mountPath: /app/config/default
    # This will be parsed through the `tpl` function.
    configName: '{{ include "openmatch.configmap.default" . }}'
  override:
    volumeName: om-config-volume-override
    mountPath: /app/config/override
    # This will be parsed through the `tpl` function.
    configName: '{{ include "openmatch.configmap.override" . }}'

open-match-override:
  enabled: true

# Override Redis settings
# https://hub.helm.sh/charts/stable/redis
# https://github.com/helm/charts/tree/master/stable/redis
redis:
  redisPort: 6379
  usePassword: false
  usePasswordFile: false
  secretMountPath: /opt/bitnami/redis/secrets
  configmap: |
    maxclients 100000
    maxmemory 500000000
  sentinel:
    enabled: true
    masterSet: om-redis-master
    port: 26379
  master:
    disableCommands: [] # don't disable 'FLUSH-' commands
    resources:
      requests:
        memory: 3Gi
        cpu: 3
      limits:
        memory: 6Gi
        cpu: 6
    persistence:
      enabled: false
    nodeSelector:
      cloud.google.com/gke-nodepool: "open-match"
  metrics:
    enabled: true
  cluster:
    slaveCount: 3
  serviceAccount:
    create: true
  slave:
    persistence:
      enabled: false
    resources:
      requests:
        memory: 1Gi
        cpu: 1
      limits:
        memory: 2Gi
        cpu: 2
    nodeSelector:
      cloud.google.com/gke-nodepool: "open-match"
  sysctlImage:
    # Enable this setting in production if you are running Open Match under Linux environment
    enabled: true
    mountHostSys: true
    # Redis may require some changes in the kernel of the host machine to work as expected,
    # in particular increasing the somaxconn value and disabling transparent huge pages.
    # https://github.com/helm/charts/tree/master/stable/redis#host-kernel-settings
    command:
      - /bin/sh
      - -c
      - |-
        echo never > /host-sys/kernel/mm/transparent_hugepage/enabled # Disable THP support
        install_packages procps
        sysctl -w net.core.somaxconn=100000
###############################################################################################################################
#                               Open Match configurations for the subcharts
#
# Open Match uses subcharts to control its `functional granularity`.
# You are able to override configurations in a subchart by having a key-value pair under its corresponding subchart section.
#
# 1. open-match-telemetry: Kubernetes definitions of the integrated monitoring tools along with the core Open Match componenets.
# 2. open-match-customize: Kubernetes definitions of the customizable template to use Open Match with your own MMFs and Evaluator.
###############################################################################################################################

# Controls if users need to install backend, frontend, query, om-configmap, and swaggerui.
open-match-core:
  enabled: true

  # Length of time between first fetch matches call, and when no further fetch
  # matches calls will join the current evaluation/synchronization cycle,
  # instead waiting for the next cycle.
  registrationInterval: 250ms
  # Length of time after match function as started before it will be canceled,
  # and evaluator call input is EOF.
  proposalCollectionInterval: 20s
  # Time after a ticket has been returned from fetch matches (marked as pending)
  # before it automatically becomes active again and will be returned by query
  # calls.
  pendingReleaseTimeout: 1m
  # Time after a ticket has been assigned before it is automatically delted.
  assignedDeleteTimeout: 10m
  # Maximum number of tickets to return on a single QueryTicketsResponse.
  queryPageSize: 10000
  # Duration for redis locks to expire.
  backfillLockTimeout: 1m

  redis:
    enabled: true
    # If open-match-core.redis.enabled is set to false, have Open Match components talk to this redis address instead.
    # Otherwise the default is set to the om-redis instance.
    hostname: # Your redis server address
    port: 6379
    user:
    pool:
      maxIdle: 500
      maxActive: 500
      idleTimeout: 0
      healthCheckTimeout: 300ms
  swaggerui:
    enabled: false

# Controls if users need to install scale testing setup for Open Match.
open-match-scale:
  # Switch the value between true/false to turn on/off this subchart
  enabled: false

# Controls if users need to install the monitoring tools in Open Match.
open-match-telemetry:
  # Switch the value between true/false to turn on/off this subchart
  enabled: false

# Controls if users need to install their own MMFs and Evaluator in Open Match.
open-match-customize:
  # Switch the value between true/false to turn on/off this subchart
  enabled: true
  evaluator:
    enabled: true

# Global configurations that are visible to all subcharts
global:
  image:
    tag: "1.2.0"

  kubernetes:
    # https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
    nodeSelector:
      cloud.google.com/gke-nodepool: "open-match"
    serviceAccount: "open-match"
    serviceAccountAnnotations:
      "iam.gke.io/gcp-service-account": "///////"
    tolerations: []
    # https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
    affinity: {}
    horizontalPodAutoScaler:
      minReplicas: 3
      maxReplicas: 10
      targetCPUUtilizationPercentage: 60
    resources:
      requests:
        memory: 1.5Gi
        cpu: 1.5
      limits:
        memory: 3Gi
        cpu: 2

  gcpProjectId: "////////"

  # Defines if Open Match needs to serve secure traffic
  tls:
    enabled: false
    server:
      mountPath: /app/secrets/tls/server
    rootca:
      mountPath: /app/secrets/tls/rootca

  logging:
    rpc:
      enabled: false

  # Expose the telemetry configurations to all subcharts because prometheus, for example,
  # requires pod-level annotation to customize its scrape path.
  # See definitions in templates/_helpers.tpl - "prometheus.annotations" section for details
  telemetry:
    reportingPeriod: "1m"
    traceSamplingFraction: 0.005 # What fraction of traces to sample.
    zpages:
      enabled: true
    jaeger:
      enabled: false
      agentEndpoint: '{{ include "openmatch.jaeger.agent" . }}'
      collectorEndpoint: '{{ include "openmatch.jaeger.collector" . }}'
    prometheus:
      enabled: false
      endpoint: "/metrics"
      serviceDiscovery: true
    stackdriverMetrics:
      enabled: false
      prefix: "open_match"
    grafana:
      enabled: false
```
